### ISSUE TITLE
pathlib

### ISSUE THREAD

**Issue by MnyCaek** [lth-elm/tradingview-webhook-trading-bot#5]
Hello,

just wanted to point out that i've had issues deploying the project to Heroku because of pathlib. 
I have replaced pathlib with pathlib2==2.3.6 in the requirements and it has succesfully deployed. 
I have not tested it yet to see if it throws any issues when running the app.

**Comment by lth-elm** [comment]
OK nice thanks for the report, if you ever test it let me know how it goes.
