### ISSUE TITLE
Request to support Binance, FTX is no longer available

### ISSUE THREAD

**Issue by cnwpdb** [lth-elm/tradingview-webhook-trading-bot#9]
If you have time, can you update support for Binance?

**Comment by lth-elm** [comment]
Hi, I'm sorry but I'm moving on with other projects and this can take some time to be integrated

**Comment by lopatamd** [comment]
@cnwpdb  meanwhile you can use wundertrading since they fortunately offer a free plan for 1 bot only as a workaround
